version: '3.9'

services:

  db:
    container_name: simulated_db
    image: mysql:python
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test_db"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/:/db/

volumes:
  db:
    driver: local